"""Generates candidate natural-language golden questions from a newly
discovered schema -- Prompt 08 (`08_ONBOARDING_ENGINE_CONTRACT.md`)'s
"golden questions" stage.

Deliberately **template-based, not LLM-generated** -- per the master
contract's rule 5 ("never allow the LLM to bypass deterministic security
controls") and this module's own need to be fully offline-testable, every
candidate question is built from already-inferred semantic labels
(`onboarding.semantic_inference`) via a small, fixed set of question
shapes, never a model call. Every candidate is
`agent.provenance.DataTruthLevel.AI_INFERENCE` and becomes an
`OnboardingReviewItem` an SME must confirm before it's promoted into
`embeddings.golden_examples` (the real, human-approved few-shot store) --
this module never writes there directly.
"""

from __future__ import annotations

from dataclasses import dataclass

from agent.provenance import DataTruthLevel
from db.relationship_inference import InferredRelationship
from onboarding.semantic_inference import SemanticLabel

_MAX_QUESTIONS_DEFAULT = 20


@dataclass(frozen=True)
class GoldenQuestionCandidate:
    """One template-generated candidate question -- never a confirmed
    golden example. `truth_level` is always `AI_INFERENCE`.

    `candidate_sql` is generated by the exact same deterministic
    template (never an LLM) -- it exists for two reasons: an SME
    reviewer sees literally what SQL this question would produce, not
    just the NL text, and `onboarding.evaluation` can smoke-test it
    directly against the live connection without needing the full
    `agent.graph.run_agent` pipeline (which assumes a database already
    published into `Settings.databases` and embedded into Chroma --
    neither true yet at onboarding time, see that module's own
    docstring). Plain, unquoted `table.column` SQL -- identifier quoting
    is deliberately left to whatever later re-validates it
    (`agent.sql_validator.validate_sql` already handles quoting/dialect
    concerns on the real query path), consistent with `retrieval
    .chunking`'s own join-condition rendering.
    """

    question: str
    tables_involved: tuple[str, ...]
    question_type: str
    confidence: float
    candidate_sql: str
    truth_level: DataTruthLevel = DataTruthLevel.AI_INFERENCE


def generate_candidate_questions(
    semantic_labels: list[SemanticLabel],
    relationships: list[InferredRelationship] | None = None,
    max_questions: int = _MAX_QUESTIONS_DEFAULT,
) -> list[GoldenQuestionCandidate]:
    """Builds candidate questions from already-inferred semantic labels.

    Shapes, in priority order (a table with both a measure and a category
    column contributes more than one):
      - **count**: `"How many rows are in {table}?"` -- one per table
        that has any column at all, the simplest possible sanity check.
      - **aggregate_by_category**: `"What is the total {measure} by
        {category}?"` -- one per (measure, category) pair in the same
        table.
      - **top_n**: `"What are the top 5 {category} values by total
        {measure}?"` -- the same pairs, a second, slightly harder shape.
      - **join_count**: `"How many {source_table} rows are there for
        each {target_table}?"` -- one per relationship (declared or
        candidate), so a join gets exercised too.

    Args:
        max_questions: A hard cap, applied after generation -- earlier
            shapes (count, then aggregate, then top-N, then join) are
            kept preferentially so a small schema's simplest, most
            reliable questions are never crowded out by a large schema's
            many join candidates.
    """
    relationships = relationships or []
    by_table: dict[str, list[SemanticLabel]] = {}
    for label in semantic_labels:
        by_table.setdefault(label.table_name, []).append(label)

    candidates: list[GoldenQuestionCandidate] = []

    for table_name in sorted(by_table):
        candidates.append(
            GoldenQuestionCandidate(
                question=f"How many rows are in {table_name}?",
                tables_involved=(table_name,),
                question_type="count",
                confidence=0.9,
                candidate_sql=f"SELECT COUNT(*) FROM {table_name}",
            )
        )

    for table_name, labels in sorted(by_table.items()):
        measures = [label for label in labels if label.label == "measure"]
        categories = [label for label in labels if label.label == "category"]
        for measure in measures:
            for category in categories:
                confidence = round(
                    0.75
                    * (0.9 if measure.is_ambiguous else 1.0)
                    * (0.9 if category.is_ambiguous else 1.0),
                    4,
                )
                candidates.append(
                    GoldenQuestionCandidate(
                        question=(
                            f"What is the total {measure.column_name} by "
                            f"{category.column_name} in {table_name}?"
                        ),
                        tables_involved=(table_name,),
                        question_type="aggregate_by_category",
                        confidence=confidence,
                        candidate_sql=(
                            f"SELECT {category.column_name}, SUM({measure.column_name}) "
                            f"FROM {table_name} GROUP BY {category.column_name}"
                        ),
                    )
                )
    for table_name, labels in sorted(by_table.items()):
        measures = [label for label in labels if label.label == "measure"]
        categories = [label for label in labels if label.label == "category"]
        for measure in measures:
            for category in categories:
                confidence = round(
                    0.65
                    * (0.9 if measure.is_ambiguous else 1.0)
                    * (0.9 if category.is_ambiguous else 1.0),
                    4,
                )
                candidates.append(
                    GoldenQuestionCandidate(
                        question=(
                            f"What are the top 5 {category.column_name} values by total "
                            f"{measure.column_name} in {table_name}?"
                        ),
                        tables_involved=(table_name,),
                        question_type="top_n",
                        confidence=confidence,
                        candidate_sql=(
                            f"SELECT {category.column_name}, SUM({measure.column_name}) AS total "
                            f"FROM {table_name} GROUP BY {category.column_name} "
                            f"ORDER BY total DESC"
                        ),
                    )
                )

    for relationship in relationships:
        source_column = relationship.source_columns[0]
        target_column = relationship.target_columns[0]
        candidates.append(
            GoldenQuestionCandidate(
                question=(
                    f"How many {relationship.source_table} rows are there for each "
                    f"{relationship.target_table}?"
                ),
                tables_involved=(relationship.source_table, relationship.target_table),
                question_type="join_count",
                confidence=round(0.6 * relationship.confidence, 4),
                candidate_sql=(
                    f"SELECT t.{target_column}, COUNT(*) FROM {relationship.source_table} s "
                    f"JOIN {relationship.target_table} t ON s.{source_column} = t.{target_column} "
                    f"GROUP BY t.{target_column}"
                ),
            )
        )

    return candidates[:max_questions]
